### ISSUE TITLE
Umbrella 0.1.0

### ISSUE THREAD

**Issue by frostney** [freezedev/flockn#1]
- [X] Canvas renderer
- [X] Serialization
- [X] Deserialization
- [X] Documentation
- [ ] Examples
- [X] Unit tests
- [ ] Default behaviors (e.g. sprite animation, collision)
- [ ] Audio
- [ ] Preloader/Assetloader
- [ ] Tweening
- [ ] Github page
- [ ] Fix DOM renderer
- [ ] Use Karma test runner

**Comment by frostney** [comment]
Actually, version-wise it will be 1.0.0, not 0.1.0
